feat:build executable sdk implementation
go-vela/sdk-go pull request #250
Opened 2023-08-23 19:44 UTC by claire1618

2023-08-23 20:19 UTC, ecrupper requested changes
minor nit, otherwise looks good

2023-08-23 20:19 UTC, ecrupper commented on vela/build.go
> +// Get returns the provided build executable.
```suggestion
// GetBuildExecutable returns the executable for the provided build.
```

2023-08-24 03:07 UTC, wass3r approved these changes

2023-08-24 13:22 UTC, ecrupper approved these changes

2023-08-24 13:35 UTC, merged