feat: add functions for hitting the `/workers` api endpoints
go-vela/sdk-go pull request #62
Opened 2020-10-19 18:06 UTC by meinenec

2020-10-19 18:39 UTC, meinenec commented on vela/worker_test.go
> +func ExampleWorkerService_Get() {
these lines are similar, but not duplicative. Even the very first line reference is different.

2020-10-20 13:24 UTC, kneal requested changes

2020-10-20 13:24 UTC, kneal commented on vela/worker_test.go
> +	repo, resp, err := c.Worker.Update("worker_1", &req)
Believe this should be `repo` -> `worker`

2020-10-20 13:24 UTC, kneal commented on vela/worker_test.go
> +	fmt.Printf("Received response code %d, for repo %+v", resp.StatusCode, repo)
Believe this should be `repo` -> `worker`

2020-10-23 13:13 UTC, kneal approved these changes
LGTM 🐬

2020-10-23 13:13 UTC, merged