feat: add admin endpoints
go-vela/sdk-go pull request #64
Opened 2020-11-16 17:41 UTC by kneal

This PR adds all the [admin]() endpoints to the SDK to make them available to admins who need to script against the endpoints.

The following is example syntax to access the admin endpoints on a client:

```go
client.Admin.Build.GetAll(nil)
```

_Note: GoDoc examples was not added at this time but can be if we think it's valuable._

Dependent PRs:
https://github.com/go-vela/mock/pull/75

2020-11-25 21:03 UTC, wass3r reviewed
conflicts need to be resolved - not sure if you noticed.

2020-11-30 13:35 UTC, jbrockopp requested changes
One small typo 👍

2020-11-30 13:35 UTC, jbrockopp commented on vela/admin.go
> +	// the server methods of the Vela API.
```suggestion
	// AdminService handles retrieving resources from
	// the server methods of the Vela API.
```

2020-11-30 14:47 UTC, jbrockopp approved these changes
LGTM

2020-11-30 21:00 UTC, meinenec approved these changes

2020-12-03 16:54 UTC, merged